import type { GlobalConfig } from 'payload'

export const Homepage: GlobalConfig = {
  slug: 'homepage',
  label: 'Homepage',
  access: {
    read: () => true,
  },
  fields: [
    { name: 'metadataTitle', type: 'text', required: true },
    { name: 'metadataDescription', type: 'textarea', required: true },
    { name: 'navbarBrand', type: 'text', required: true },
    { name: 'heroBadgeText', type: 'text', required: true },
    { name: 'heroBadgeCta', type: 'text', required: true },
    { name: 'heroBadgeHref', type: 'text', required: true },
    { name: 'heroHeadline', type: 'text', required: true },
    { name: 'heroDescription', type: 'textarea', required: true },
    { name: 'heroInstallSnippet', type: 'text', required: true },
    { name: 'heroPrimaryCtaLabel', type: 'text', required: true },
    { name: 'heroPrimaryCtaHref', type: 'text', required: true },
    { name: 'heroSecondaryCtaLabel', type: 'text', required: true },
    { name: 'heroSecondaryCtaHref', type: 'text', required: true },
    {
      name: 'heroMobileScreenshot',
      type: 'upload',
      relationTo: 'media',
      required: true,
    },
    { name: 'heroMobileScreenshotAlt', type: 'text', required: true },
    {
      name: 'heroDesktopScreenshot',
      type: 'upload',
      relationTo: 'media',
      required: true,
    },
    { name: 'heroDesktopScreenshotAlt', type: 'text', required: true },
    {
      name: 'commonProblems',
      type: 'array',
      required: true,
      fields: [{ name: 'text', type: 'text', required: true }],
    },
    { name: 'solutionTitle', type: 'text', required: true },
    { name: 'solutionDescription', type: 'textarea', required: true },
    {
      name: 'starterFeatures',
      type: 'array',
      required: true,
      fields: [
        { name: 'title', type: 'text', required: true },
        { name: 'description', type: 'textarea', required: true },
      ],
    },
    {
      name: 'demoFeatures',
      type: 'array',
      required: true,
      fields: [
        { name: 'headline', type: 'text', required: true },
        { name: 'subheadline', type: 'textarea', required: true },
        {
          name: 'imageSrc',
          type: 'upload',
          relationTo: 'media',
          required: true,
        },
        { name: 'imageAlt', type: 'text', required: true },
        {
          name: 'wallpaper',
          type: 'select',
          required: true,
          options: ['blue', 'green', 'purple', 'brown'],
        },
        {
          name: 'placement',
          type: 'select',
          required: true,
          options: ['bottom', 'bottom-left', 'bottom-right'],
        },
        { name: 'ctaHref', type: 'text', required: true },
        { name: 'ctaLabel', type: 'text', required: true },
      ],
    },
    {
      name: 'starterWorkflow',
      type: 'array',
      required: true,
      fields: [
        { name: 'step', type: 'text', required: true },
        { name: 'title', type: 'text', required: true },
        { name: 'description', type: 'textarea', required: true },
      ],
    },
    { name: 'footerFineprint', type: 'text', required: true },
    { name: 'footerPrimaryCtaLabel', type: 'text', required: true },
    { name: 'footerPrimaryCtaHref', type: 'text', required: true },
  ],
}
