import type { GlobalConfig } from 'payload'

export const Pricing: GlobalConfig = {
  slug: 'pricing',
  label: 'Pricing',
  access: {
    read: () => true,
  },
  fields: [
    { name: 'metadataTitle', type: 'text', required: true },
    { name: 'metadataDescription', type: 'textarea', required: true },
    { name: 'navbarBrand', type: 'text', required: true },
    { name: 'heroHeadline', type: 'text', required: true },
    { name: 'heroSubheadline', type: 'textarea', required: true },
    {
      name: 'plans',
      type: 'array',
      required: true,
      minRows: 3,
      maxRows: 3,
      fields: [
        { name: 'name', type: 'text', required: true },
        { name: 'badge', type: 'text' },
        { name: 'monthlyPrice', type: 'text', required: true },
        { name: 'yearlyPrice', type: 'text', required: true },
        { name: 'periodLabel', type: 'text', required: true },
        { name: 'subheadline', type: 'textarea', required: true },
        {
          name: 'features',
          type: 'array',
          required: true,
          fields: [{ name: 'text', type: 'text', required: true }],
        },
        { name: 'ctaLabel', type: 'text', required: true },
        { name: 'ctaHref', type: 'text', required: true },
        {
          name: 'ctaVariant',
          type: 'select',
          required: true,
          options: ['primary', 'soft'],
          defaultValue: 'soft',
        },
      ],
    },
    {
      name: 'comparisonSections',
      type: 'array',
      required: true,
      fields: [
        { name: 'title', type: 'text', required: true },
        {
          name: 'features',
          type: 'array',
          required: true,
          fields: [
            { name: 'name', type: 'text', required: true },
            {
              name: 'starterIncluded',
              type: 'checkbox',
              defaultValue: false,
              required: true,
            },
            { name: 'starterValue', type: 'text' },
            {
              name: 'growthIncluded',
              type: 'checkbox',
              defaultValue: false,
              required: true,
            },
            { name: 'growthValue', type: 'text' },
            {
              name: 'proIncluded',
              type: 'checkbox',
              defaultValue: false,
              required: true,
            },
            { name: 'proValue', type: 'text' },
          ],
        },
      ],
    },
    { name: 'testimonialQuote', type: 'textarea', required: true },
    { name: 'testimonialName', type: 'text', required: true },
    { name: 'testimonialByline', type: 'text', required: true },
    { name: 'testimonialImageUrl', type: 'text', required: true },
    { name: 'testimonialImageAlt', type: 'text', required: true },
    {
      name: 'faqs',
      type: 'array',
      required: true,
      fields: [
        { name: 'question', type: 'text', required: true },
        { name: 'answer', type: 'textarea', required: true },
      ],
    },
    { name: 'ctaHeadline', type: 'text', required: true },
    { name: 'ctaSubheadline', type: 'textarea', required: true },
    { name: 'ctaPrimaryLabel', type: 'text', required: true },
    { name: 'ctaPrimaryHref', type: 'text', required: true },
    { name: 'ctaSecondaryLabel', type: 'text', required: true },
    { name: 'ctaSecondaryHref', type: 'text', required: true },
    { name: 'newsletterHeadline', type: 'text', required: true },
    { name: 'newsletterSubheadline', type: 'textarea', required: true },
    { name: 'newsletterAction', type: 'text', required: true },
    {
      name: 'footerCategories',
      type: 'array',
      required: true,
      fields: [
        { name: 'title', type: 'text', required: true },
        {
          name: 'links',
          type: 'array',
          required: true,
          fields: [
            { name: 'label', type: 'text', required: true },
            { name: 'href', type: 'text', required: true },
          ],
        },
      ],
    },
    { name: 'footerFineprint', type: 'text', required: true },
    { name: 'xUrl', type: 'text', required: true },
    { name: 'githubUrl', type: 'text', required: true },
    { name: 'youtubeUrl', type: 'text', required: true },
  ],
}
