/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'homepage-testimonials': HomepageTestimonial;
    logos: Logo;
    faqs: Faq;
    'blog-categories': BlogCategory;
    blogs: Blog;
    'join-waitlist': JoinWaitlist;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'homepage-testimonials': HomepageTestimonialsSelect<false> | HomepageTestimonialsSelect<true>;
    logos: LogosSelect<false> | LogosSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'blog-categories': BlogCategoriesSelect<false> | BlogCategoriesSelect<true>;
    blogs: BlogsSelect<false> | BlogsSelect<true>;
    'join-waitlist': JoinWaitlistSelect<false> | JoinWaitlistSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
    pricing: Pricing;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    pricing: PricingSelect<false> | PricingSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-testimonials".
 */
export interface HomepageTestimonial {
  id: number;
  quote: string;
  name: string;
  byline: string;
  avatar: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "logos".
 */
export interface Logo {
  id: number;
  name: string;
  image: number | Media;
  width: number;
  height: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  /**
   * Lower numbers appear first.
   */
  order: number;
  question: string;
  answer: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories".
 */
export interface BlogCategory {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs".
 */
export interface Blog {
  id: number;
  coverImage: number | Media;
  slug: string;
  title: string;
  excerpt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  author: number | User;
  status: 'draft' | 'published' | 'archived' | 'scheduled';
  scheduledAt?: string | null;
  category: number | BlogCategory;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  readingTimeMinutes: number;
  metaTitle?: string | null;
  metaDescription?: string | null;
  metaKeywords?:
    | {
        keyword: string;
        id?: string | null;
      }[]
    | null;
  canonicalUrl?: string | null;
  isPinned?: boolean | null;
  /**
   * Custom JSON-LD schema data for this blog post (Article, FAQPage, HowTo, etc.).
   */
  structuredData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "join-waitlist".
 */
export interface JoinWaitlist {
  id: number;
  email: string;
  fullName: string;
  companyName?: string | null;
  jobTitle?: string | null;
  companyWebsite?: string | null;
  teamSize?: ('1' | '2-10' | '11-50' | '51-200' | '201-1000' | '1000+') | null;
  useCase?: string | null;
  biggestChallenge?: string | null;
  expectedMonthlyVolume?: number | null;
  status: 'new' | 'contacted' | 'invited' | 'converted' | 'archived';
  priority?: ('low' | 'medium' | 'high') | null;
  notes?: string | null;
  /**
   * User accepted terms and privacy policy during waitlist signup.
   */
  consentToTerms: boolean;
  consentToMarketing?: boolean | null;
  attribution?: {
    /**
     * High-level acquisition source (e.g. organic, referral, ad).
     */
    source?: string | null;
    campaign?: string | null;
    utmSource?: string | null;
    utmMedium?: string | null;
    utmCampaign?: string | null;
    utmTerm?: string | null;
    utmContent?: string | null;
    referrer?: string | null;
  };
  technicalMetadata?: {
    ipAddress?: string | null;
    userAgent?: string | null;
    locale?: string | null;
    timezone?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'homepage-testimonials';
        value: number | HomepageTestimonial;
      } | null)
    | ({
        relationTo: 'logos';
        value: number | Logo;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'blog-categories';
        value: number | BlogCategory;
      } | null)
    | ({
        relationTo: 'blogs';
        value: number | Blog;
      } | null)
    | ({
        relationTo: 'join-waitlist';
        value: number | JoinWaitlist;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-testimonials_select".
 */
export interface HomepageTestimonialsSelect<T extends boolean = true> {
  quote?: T;
  name?: T;
  byline?: T;
  avatar?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "logos_select".
 */
export interface LogosSelect<T extends boolean = true> {
  name?: T;
  image?: T;
  width?: T;
  height?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  order?: T;
  question?: T;
  answer?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories_select".
 */
export interface BlogCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs_select".
 */
export interface BlogsSelect<T extends boolean = true> {
  coverImage?: T;
  slug?: T;
  title?: T;
  excerpt?: T;
  content?: T;
  author?: T;
  status?: T;
  scheduledAt?: T;
  category?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  readingTimeMinutes?: T;
  metaTitle?: T;
  metaDescription?: T;
  metaKeywords?:
    | T
    | {
        keyword?: T;
        id?: T;
      };
  canonicalUrl?: T;
  isPinned?: T;
  structuredData?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "join-waitlist_select".
 */
export interface JoinWaitlistSelect<T extends boolean = true> {
  email?: T;
  fullName?: T;
  companyName?: T;
  jobTitle?: T;
  companyWebsite?: T;
  teamSize?: T;
  useCase?: T;
  biggestChallenge?: T;
  expectedMonthlyVolume?: T;
  status?: T;
  priority?: T;
  notes?: T;
  consentToTerms?: T;
  consentToMarketing?: T;
  attribution?:
    | T
    | {
        source?: T;
        campaign?: T;
        utmSource?: T;
        utmMedium?: T;
        utmCampaign?: T;
        utmTerm?: T;
        utmContent?: T;
        referrer?: T;
      };
  technicalMetadata?:
    | T
    | {
        ipAddress?: T;
        userAgent?: T;
        locale?: T;
        timezone?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  metadataTitle: string;
  metadataDescription: string;
  navbarBrand: string;
  heroBadgeText: string;
  heroBadgeCta: string;
  heroBadgeHref: string;
  heroHeadline: string;
  heroDescription: string;
  heroInstallSnippet: string;
  heroPrimaryCtaLabel: string;
  heroPrimaryCtaHref: string;
  heroSecondaryCtaLabel: string;
  heroSecondaryCtaHref: string;
  heroMobileScreenshot: number | Media;
  heroMobileScreenshotAlt: string;
  heroDesktopScreenshot: number | Media;
  heroDesktopScreenshotAlt: string;
  commonProblems: {
    text: string;
    id?: string | null;
  }[];
  solutionTitle: string;
  solutionDescription: string;
  starterFeatures: {
    title: string;
    description: string;
    id?: string | null;
  }[];
  demoFeatures: {
    headline: string;
    subheadline: string;
    imageSrc: number | Media;
    imageAlt: string;
    wallpaper: 'blue' | 'green' | 'purple' | 'brown';
    placement: 'bottom' | 'bottom-left' | 'bottom-right';
    ctaHref: string;
    ctaLabel: string;
    id?: string | null;
  }[];
  starterWorkflow: {
    step: string;
    title: string;
    description: string;
    id?: string | null;
  }[];
  footerFineprint: string;
  footerPrimaryCtaLabel: string;
  footerPrimaryCtaHref: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing".
 */
export interface Pricing {
  id: number;
  metadataTitle: string;
  metadataDescription: string;
  navbarBrand: string;
  heroHeadline: string;
  heroSubheadline: string;
  plans: {
    name: string;
    badge?: string | null;
    monthlyPrice: string;
    yearlyPrice: string;
    periodLabel: string;
    subheadline: string;
    features: {
      text: string;
      id?: string | null;
    }[];
    ctaLabel: string;
    ctaHref: string;
    ctaVariant: 'primary' | 'soft';
    id?: string | null;
  }[];
  comparisonSections: {
    title: string;
    features: {
      name: string;
      starterIncluded: boolean;
      starterValue?: string | null;
      growthIncluded: boolean;
      growthValue?: string | null;
      proIncluded: boolean;
      proValue?: string | null;
      id?: string | null;
    }[];
    id?: string | null;
  }[];
  testimonialQuote: string;
  testimonialName: string;
  testimonialByline: string;
  testimonialImageUrl: string;
  testimonialImageAlt: string;
  faqs: {
    question: string;
    answer: string;
    id?: string | null;
  }[];
  ctaHeadline: string;
  ctaSubheadline: string;
  ctaPrimaryLabel: string;
  ctaPrimaryHref: string;
  ctaSecondaryLabel: string;
  ctaSecondaryHref: string;
  newsletterHeadline: string;
  newsletterSubheadline: string;
  newsletterAction: string;
  footerCategories: {
    title: string;
    links: {
      label: string;
      href: string;
      id?: string | null;
    }[];
    id?: string | null;
  }[];
  footerFineprint: string;
  xUrl: string;
  githubUrl: string;
  youtubeUrl: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  metadataTitle?: T;
  metadataDescription?: T;
  navbarBrand?: T;
  heroBadgeText?: T;
  heroBadgeCta?: T;
  heroBadgeHref?: T;
  heroHeadline?: T;
  heroDescription?: T;
  heroInstallSnippet?: T;
  heroPrimaryCtaLabel?: T;
  heroPrimaryCtaHref?: T;
  heroSecondaryCtaLabel?: T;
  heroSecondaryCtaHref?: T;
  heroMobileScreenshot?: T;
  heroMobileScreenshotAlt?: T;
  heroDesktopScreenshot?: T;
  heroDesktopScreenshotAlt?: T;
  commonProblems?:
    | T
    | {
        text?: T;
        id?: T;
      };
  solutionTitle?: T;
  solutionDescription?: T;
  starterFeatures?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  demoFeatures?:
    | T
    | {
        headline?: T;
        subheadline?: T;
        imageSrc?: T;
        imageAlt?: T;
        wallpaper?: T;
        placement?: T;
        ctaHref?: T;
        ctaLabel?: T;
        id?: T;
      };
  starterWorkflow?:
    | T
    | {
        step?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  footerFineprint?: T;
  footerPrimaryCtaLabel?: T;
  footerPrimaryCtaHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing_select".
 */
export interface PricingSelect<T extends boolean = true> {
  metadataTitle?: T;
  metadataDescription?: T;
  navbarBrand?: T;
  heroHeadline?: T;
  heroSubheadline?: T;
  plans?:
    | T
    | {
        name?: T;
        badge?: T;
        monthlyPrice?: T;
        yearlyPrice?: T;
        periodLabel?: T;
        subheadline?: T;
        features?:
          | T
          | {
              text?: T;
              id?: T;
            };
        ctaLabel?: T;
        ctaHref?: T;
        ctaVariant?: T;
        id?: T;
      };
  comparisonSections?:
    | T
    | {
        title?: T;
        features?:
          | T
          | {
              name?: T;
              starterIncluded?: T;
              starterValue?: T;
              growthIncluded?: T;
              growthValue?: T;
              proIncluded?: T;
              proValue?: T;
              id?: T;
            };
        id?: T;
      };
  testimonialQuote?: T;
  testimonialName?: T;
  testimonialByline?: T;
  testimonialImageUrl?: T;
  testimonialImageAlt?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  ctaHeadline?: T;
  ctaSubheadline?: T;
  ctaPrimaryLabel?: T;
  ctaPrimaryHref?: T;
  ctaSecondaryLabel?: T;
  ctaSecondaryHref?: T;
  newsletterHeadline?: T;
  newsletterSubheadline?: T;
  newsletterAction?: T;
  footerCategories?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  footerFineprint?: T;
  xUrl?: T;
  githubUrl?: T;
  youtubeUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}